### ISSUE TITLE
Update wiring schematic for wiki

### ISSUE THREAD

**Issue by gemueseeintopf** [elheck/Squiddrone#162]
Update schematic  with tranceiver IRQ path

**Comment by gemueseeintopf** [comment]
![scematic_drone_wiring](https://user-images.githubusercontent.com/53154201/74875730-0771fd00-5363-11ea-8308-0bb35cc6afb7.png)

**Comment by gemueseeintopf** [comment]
Link from upper comment added to wiki

**Comment by c0nwild** [comment]
LGTM
