### ISSUE TITLE
Rearrange visual paradim project structure

### ISSUE THREAD

**Issue by c0nwild** [elheck/Squiddrone#180]
- All component specific software parts (i.e. drivers) will be located in SquidDrone_PartsCatalogue package along with the corresponding component.
- Higher level software components will be located in the Squiddrone_software package.

**Comment by c0nwild** [comment]
Revision for review: 31	Conradwild	2020 Apr 12, 21:57:28

**Comment by elheck** [comment]
LGTM - I like the new project structure much more now. Thanks
