### ISSUE TITLE
Wiki entry - unified doxygen documentation style

### ISSUE THREAD

**Issue by elheck** [elheck/Squiddrone#193]

**Comment by c0nwild** [comment]
First draw here: https://github.com/elheck/Squiddrone/wiki/Doxygen-Style-Guide
pls. review

**Comment by elheck** [comment]
How about single line comments above the line of code? By doing this it becomes easier to read, because it is more compact and left side aligned.

Doxygen Documentation Generator generates the comments that all fist * -signs are aligned.
See [motor.hpp](https://github.com/elheck/Squiddrone/blob/dev/squidDrone/src/propulsion/motor.hpp) for reference.

In your draft, the * signs are aligned with the opening /

**Comment by c0nwild** [comment]
Alignment of multiline comments in examples is now correct.
Good idea, placing the single line comments above the code. Done.

**Comment by elheck** [comment]
LGTM
