### ISSUE TITLE
Change GPIO configuration for SPI pins

### ISSUE THREAD

**Issue by ThorsHamster** [elheck/Squiddrone#204]

**Comment by c0nwild** [comment]
- Change of GPIO speed shows improvement of signal waveform (i.e. SPI Clock signal). Blue: Before, Red: After.
![A7BD516D-EDF0-412C-8018-2D3C837D27D5](https://user-images.githubusercontent.com/42233292/81064943-e25d4700-8eda-11ea-96b4-ce4606a8225a.jpeg)
- SPI datasize of 8 bit required for bytewise transfer.
