### ISSUE TITLE
Adjust clang-format to google styleguide

### ISSUE THREAD

**Issue by ThorsHamster** [elheck/Squiddrone#234]
- Adjust doxygen documentation
- Adjust include order

**Comment by ThorsHamster** [comment]
Tried to find a solution, but it seems there is no solution for the doxygen comments. The formatting of clang-format also seems to be correct, it is just not formatting the whole comment.

**Comment by ThorsHamster** [comment]
The sorting of includes can be "broken" with a line inbetween.
For example:

`#include "stm32g4xx.h"`
`// stm32g4xx.h has to be first`
`#include "error_types.hpp"`

will prevent the sorting of clang-format.

Would this resolve your problem, @elheck 

Furthermore we can additionally set clang-format to "IBS_Preserve".
See here: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by elheck** [comment]
@ThorsHamster  yes the comment line inbetween solves my problem
