### ISSUE TITLE
Update Wiki regarding tools used (No more travis e.g)

### ISSUE THREAD

**Issue by elheck** [elheck/Squiddrone#295]
Changed [this Wiki entry](https://github.com/Squiddrone/Squiddrone/wiki/Review-procedure)

-Link changed from TravisCi to Build Action.
-Link changed from ReportCi to Test Action.
Both links are in [this](https://github.com/Squiddrone/Squiddrone/wiki/Review-procedure) wiki entry

**Comment by c0nwild** [comment]
LGTM
