### ISSUE TITLE
Fix gitpod docker repo link

### ISSUE THREAD

**Issue by elheck** [elheck/Squiddrone#296]
The link was correct, it should point to the dockerhub image which still is the same address.

Cannot be fixed by us. It seems to be a problem by gitpod since they changed their layer. 

I asked them to reopen an issue about this. We will have to see.

https://github.com/gitpod-io/gitpod/issues/1439

**Comment by c0nwild** [comment]
How do we proceed in order not to lose track of the issue ourselves?

**Comment by elheck** [comment]
@c0nwild Well, we wait until github fully releases codespaces and then we don't care anymore. I think Gitpod stopped developing on old issues, because they know they might become irrelevant.
